# Generated by Django 4.2.2 on 2023-06-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0002_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Timestamp',
            field=models.DateTimeField(default='2023-06-30T19:27:19.614393Z'),
            preserve_default=False,
        ),
    ]
