# Generated by Django 4.2.2 on 2023-06-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0003_subscriptions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
